version: 2.1

jobs:
  install:
    docker:
      - image: cimg/node:20.1.0
    working_directory: /home/circleci/repo 
    steps:
      - checkout
      - run: npm install

  build:
    docker:
      - image: cimg/node:20.1.0
    working_directory: /home/circleci/repo/
    steps:
      - checkout
      - run: npm install
      - run: npm run build

workflows:
  install_and_build:
    jobs:
      - install
      - build
